#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x6_3(
		_______, 	LT(4,KC_Q), 	KC_W, 			KC_E, 			KC_R, 			KC_T, 			KC_Y, 			KC_U, 			KC_I, 			KC_O, 			KC_P, 			_______, 
		_______, 	LSA_T(KC_A), 	KC_S, 			KC_D, 			KC_F, 			KC_G, 			KC_H, 			KC_J, 			KC_K, 			KC_L, 			KC_SCLN, 		_______, 
		_______, 	LSFT_T(KC_Z), 	KC_X, 			KC_C, 			KC_V, 			KC_B, 			KC_N, 			KC_M, 			KC_COMM, 		KC_DOT, 		LSFT_T(KC_SLSH),_______, 
													MO(3), 			LT(2,KC_ESC), 	LT(1,KC_ENT), 	LT(1,KC_BSPC), 	LCTL_T(KC_SPC), KC_NO),
	[1] = LAYOUT_split_3x6_3(
		_______, 	KC_TAB, 		_______, 		_______,		_______, 		_______, 		_______,		_______, 		_______, 		_______, 		KC_DEL,			_______, 
		_______, 	_______, 		_______, 		_______, 		_______, 		_______, 		KC_LEFT, 		KC_DOWN, 		KC_UP, 			KC_RGHT, 		_______, 		_______, 
		_______, 	_______, 		_______,		_______,		_______, 		_______, 		_______, 		_______, 		_______, 		_______, 		_______, 		_______, 
													_______, 		_______, 		_______, 		_______, 		_______, 		_______),

	[2] = LAYOUT_split_3x6_3(
		_______, 	KC_EXLM, 		KC_AT, 			KC_HASH,		KC_DLR, 		KC_PERC, 		KC_CIRC, 		KC_AMPR, 		KC_ASTR, 		KC_PLUS, 		KC_EQL, 		_______, 
		_______, 	KC_TILD, 		KC_GRV, 		KC_LCBR, 		KC_LPRN, 		KC_LBRC, 		KC_RBRC, 		KC_RPRN, 		KC_RCBR, 		KC_MINS, 		KC_UNDS, 		_______, 
		_______, 	_______, 		_______, 		_______, 		_______,		_______, 		KC_PIPE, 		_______, 		KC_LT, 			KC_GT, 			KC_BSLS, 		_______, 
													_______, 		_______, 		_______, 		_______, 		_______,		_______),

	[3] = LAYOUT_split_3x6_3(
		_______, 	_______, 		_______, 		_______, 		_______, 		_______, 		KC_7, 			KC_8, 			KC_9, 			_______, 		_______, 		_______, 
		_______, 	_______, 		_______, 		_______, 		_______, 		_______, 		KC_4, 			KC_5, 			KC_6, 			_______, 		_______, 		_______, 
		_______, 	_______, 		_______, 		_______, 		_______, 		_______, 		KC_1, 			KC_2, 			KC_3, 			_______, 		_______, 		_______, 
													_______, 		_______, 		_______, 		_______, 		KC_0, 			KC_DOT),

	[4] = LAYOUT_split_3x6_3(
		_______, 	KC_TRNS, 		_______, 		_______, 		_______, 		_______, 		KC_F7, 			KC_F8, 			KC_F9, 			_______, 		_______, 		_______, 
		_______, 	_______, 		_______, 		_______, 		_______, 		_______, 		KC_F4, 			KC_F5, 			KC_F6, 			_______, 		_______, 		_______, 
		_______, 	_______, 		_______, 		_______, 		_______, 		_______, 		KC_F1, 			KC_F2, 			KC_F3, 			_______, 		_______, 		_______, 
													_______, 		_______, 		_______, 		KC_F10, 		KC_F11, 		KC_F12)
};

